last_change = 2026-09-23T12:23:24.658642Z
addr = 0x4bb4a0
size = 0x9e
name = "CNetworkGameClientBase_ProcessUpdateStringTable"

[header]
name = "CNetworkGameClientBase_ProcessUpdateStringTable"
addr = 0x4bb4a0

[header.args]
