last_change = 2026-09-23T12:23:24.658944Z
addr = 0x596dd0
size = 0x54
name = "CInputService_IsClientOnlyCommandAllowed"

[header]
name = "CInputService_IsClientOnlyCommandAllowed"
addr = 0x596dd0

[header.args]
