last_change = 2026-09-23T12:23:24.658948Z
addr = 0x5a51f0
size = 0xeda
name = "CNetworkStringTableClient_ParseUpdate"

[header]
name = "CNetworkStringTableClient_ParseUpdate"
addr = 0x5a51f0

[header.args]
